[package]
name = "floo"
version = "0.1.0"
edition = "2024"
description = "Effortless travel to and from workspaces"
documentation = "https://keyvizsla.github.io/floo"
homepage = "https://keyvizsla.github.io/floo"
readme = "README.md"
repository = "https://github.com/keyvizsla/floo"
license = "GPL-3.0"
keywords = ["tui", "ratatui", "utility", "workspace", "developer-tools"]
categories = ["command-line-interface", "command-line-utilities", "development-tools", "filesystem"]

[[bin]]
name = "floo-bin"
path = "src/main.rs"

[features]
bundled = ["rusqlite/bundled"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
edit = "0.1.5"
ratatui = "0.30.0"
ratatui-interact = { version = "0.5.3-fork.1", features = ["markdown", "filesystem"], package = "ratatui-interact-fork" }
shellexpand = "3.1.2"
tui-markdown = "0.3.7"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
rusqlite = { version = "0.39.0" }
