[package]
name = "floo"
version = "0.1.0-beta.0"
edition = "2024"

[[bin]]
name = "floo-bin"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29.0"
edit = "0.1.5"
ratatui = "0.30.0"
# Disabled until potentially the upstream incoroporates our changes
# ratatui-interact = { version = "0.5.3", features = ["markdown", "filesystem"] }
ratatui-interact = { git = "https://github.com/keyvizsla/ratatui-interact", features = ["markdown", "filesystem"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
shellexpand = "3.1.2"
tui-markdown = "0.3.7"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
