name: Run E2E Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/keyvizsla/floo-linux:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Run Tests
        run: |
          cargo install --path .
          python tests/e2e_test_base.py
