name: Run Tests

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      is_local:
        required: true
        type: boolean

jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull remote image
        if: ${{ !inputs.is_local }}
        run: docker pull ${{ inputs.image_tag }}

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Unittests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ${{ inputs.image_tag }} \
            cargo test
